# Generated by Django 6.0.1 on 2026-01-17 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0004_tenant_alter_unit_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_records', to='properties.tenancy')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rent_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.rentrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='rentrecord',
            index=models.Index(fields=['tenancy', 'year', 'month'], name='payments_re_tenancy_41f6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='rentrecord',
            index=models.Index(fields=['status'], name='payments_re_status_8ca77c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rentrecord',
            unique_together={('tenancy', 'year', 'month')},
        ),
    ]
