# Generated by Django 6.0.1 on 2026-01-08 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caretakers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'CARETAKER'}, related_name='assigned_apartments', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(limit_choices_to={'role': 'LANDLORD'}, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
