# Generated by Django 6.0.1 on 2026-01-09 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='caretakers',
        ),
        migrations.AddField(
            model_name='apartment',
            name='caretakers',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CARETAKER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
